<a href="https://colab.research.google.com/github/roly-3618/114-2_coding/blob/main/%E3%80%8CHW1_1_%E6%97%A5%E5%B8%B8%E6%94%AF%E5%87%BA%E9%80%9F%E7%AE%97%E8%88%87%E5%88%86%E6%94%A4_ipynb%E3%80%8D%E7%9A%84%E5%89%AF%E6%9C%AC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#日常支出速算與分攤（作業一）
- 目標：從 Sheet 讀「消費紀錄」→ 計總額/分類小計/AA 分攤 → 寫回 Sheet Summary 分頁。
- AI 點子（可選）：請模型總結本週花錢習慣與建議（例如「外食過多」）。
- Sheet 欄位：date, category, item, amount, payer

GoogleSheet: https://docs.google.com/spreadsheets/d/1f0jkB_z5XxHhVhpB2PVDENNQ_PUrb-OSHE7CGpJg6G8/edit?gid=0#gid=0

In [1]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

In [2]:
import pandas as pd
# read data and put it in a dataframe
# 在 google 工作表載入 gsheets
gsheets = gc.open_by_url('https://docs.google.com/spreadsheets/d/1f0jkB_z5XxHhVhpB2PVDENNQ_PUrb-OSHE7CGpJg6G8/edit?gid=0#gid=0')

In [30]:
# 從 gsheets 的 All-whiteboard-device 載入 sheets
sheets = gsheets.worksheet('工作表1').get_all_values()
# 將 sheets1 資料載入 pd 的 DataFrame 進行分析
df = pd.DataFrame(sheets[1:], columns=sheets[0])
# 取得最前面的5筆資料
df.head()

Empty DataFrame
Columns: []
Index: []

In [4]:
import datetime

In [36]:
# 讓使用者輸入資料
date_str = input("請輸入日期 (格式：YYYY-MM-DD): ")
# 檢查日期格式是否正確
datetime.datetime.strptime(date_str, '%Y-%m-%d')

time_str = input("請輸入時間 (格式：HH:MM): ")
# 檢查時間格式是否正確
datetime.datetime.strptime(time_str, '%H:%M')

classification = input("請輸入分類: ")
item = input("請輸入品項: ")
amount = float(input("請輸入金額: "))
person = input("請輸入付款人: ")
place = input("請輸入地點: ")
notes = input("請輸入備註: ")

請輸入日期 (格式：YYYY-MM-DD): 2026-03-03
請輸入時間 (格式：HH:MM): 08:15
請輸入分類: 早餐
請輸入品項: 蘿蔔糕
請輸入金額: 30
請輸入付款人: Gary
請輸入地點: 永和豆漿
請輸入備註: Roly有一起吃

In [37]:
date_str

'2026-03-03'

In [38]:
time_str

'08:15'

In [39]:
item

'蘿蔔糕'

In [40]:
amount

30.0

In [41]:
# 創建一個新的 DataFrame 來代表你要新增的資料
new_data = pd.DataFrame([{
    '日期': date_str,
    '時間': time_str,
    '分類': classification,
    '品項': item,
    '金額': amount,
    '付款人': person,
    '地點': place,
    '備註': notes
}])

# 使用 concat() 將新資料合併到舊的 df 中
df = pd.concat([df, new_data], ignore_index=True)

In [42]:
df

           日期     時間  分類   品項     金額   付款人    地點        備註
0  2026-03-05  09:15  宵夜  鹹酥雞  300.0  Roly  樂華夜市         無
1  2026-03-03  08:15  早餐  蘿蔔糕   30.0  Gary  永和豆漿  Roly有一起吃

In [43]:
# 將 DataFrame 轉換成列表的列表 (list of lists)，這是 gspread 支援的資料格式
data_to_write = df.values.tolist()

# 第一步：取得工作表物件
worksheet = gsheets.worksheet('工作表1')

# 第二步：將資料寫入工作表
worksheet.append_rows(values=data_to_write, value_input_option='USER_ENTERED')
print("資料已成功寫入 Google 工作表！")

資料已成功寫入 Google 工作表！